# Generated by Django 4.0.3 on 2023-04-19 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoeVO',
            new_name='BinVO',
        ),
    ]
